// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Pharm_api.Models;

public partial class StockArticulo
{
    public int CodStockArticulo { get; set; }

    public int Cantidad { get; set; }

    public int CodSucursal { get; set; }

    public int CodArticulo { get; set; }
}